name: Deploy
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - prod

jobs:
  buildAndDeploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
        
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      
      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: Deploy
        uses: serverless/github-action@master
        with:
          args: deploy -s prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}